package:
  version: 1.1.0
  url: https://github.com/pooza/kariyon
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
mix: false
slack:
  hooks: []
http:
  retry:
    limit: 3
    seconds: 1
